osx_image: xcode9.1
language: objective-c
xcode_workspace: Qwolm.xcworkspace
xcode_scheme: Qwolm_Example

script:
- xcodebuild clean build -workspace xcode_workspace -scheme xcode_scheme -sdk iphonesimulator PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild test -workspace xcode_workspace -scheme 'Qwolm_Tests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint

after_success:
- bash <(curl -s https://codecov.io/bash)
